### ISSUE TITLE
Special characters in panos_exporter.yaml

### ISSUE THREAD

**Issue by JosephSonner** [jenningsloy318/panos_exporter#18] opened 2023-01-27 14:47 UTC
If the password for the Palo Alto has special characters, the application tries to convert or interpret it as something different. 
For example !QAZ changes to %21QAZ - I have tried many different possibilities in the yaml including: 
password >
   !QAZ
"!QAZ"
'!QAZ"
\!QAZ

**Comment by pawelos99** [comment] 2023-01-29 11:41
It was caused by missing url encoding when generating the api key. Fixed in pull request.

**Comment by zbbfufu** [comment] 2023-02-01 15:13
Should be fixed now. I'll publish a new release to test it.

**Closed by zbbfufu** 2023-02-01 15:13 UTC
